FROM stilliard/pure-ftpd:hardened
RUN pure-pw useradd secureftp -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/secureftp 
RUN mkdir -p /etc/ssl/private
RUN openssl dhparam -out /etc/ssl/private/pure-ftpd-dhparams.pem 2048
RUN openssl req -x509 -nodes -newkey rsa:2048 -sha256 -keyout /etc/ssl/private/pure-ftpd.pem -out /etc/ssl/private/pure-ftpd.pem
RUN chmod 600 /etc/ssl/private/*.pem